### ISSUE TITLE
mysql.sock: connect: no such file or directory error

### ISSUE THREAD

**Issue by yashmankad** [lestrrat-go/test-mysqld#13]
Hi,
Typically when I run back to back Go tests that create a mysql daemon and close it (using ```go-test-mysqld```), the second testcase sometimes fails while accessing the daemon with the error ```sql: database is closed```.

Or sometimes the error is slightly different

```dial unix /<path-to-test-dir>/mysqltest945966494/tmp/mysql.sock: connect: no such file or directory```

If I run the testcases individually, I don't see this problem. Can you think of a reason why this might happen? Your help is much appreciated.

**Comment by yashmankad** [comment]
ok, I was able to get past the ```database closed``` error. I was closing the conneciton pool to SQL (through Go's database/sql package).

Now I consistently get the error that indicates the connection is broken.

```packets.go:130: write unix @->/testoutput/mysqltest383479528/tmp/mysql.sock: write: broken pipe

dial unix /Users/ymankad/source-code/control-plane/testoutput/mysqltest383479528/tmp/mysql.sock: connect: no such file or directory
```

**Comment by yashmankad** [comment]
I was able to find the root cause. There was no problem related to this library so I'm sorry for opening an issue against it.

The API requests were going to a stale TCP socket whose listener IP/port were closed by my application much earlier. However, Go's implementation of TCP socket prior to version 1.8 is tricky - they don't offer a ```Close()``` API call on the socket but on the listener. And closing the listener doesn't necessarily mean the socket is closed.

If a subsequent socket is opened against the same REST listener, there is a chance your API request would go to the old socket because it is not closed it. From Go 1.8, we can explicitly close a socket and that resolved the problem.

**Comment by lestrrat** [comment]
Sorry for warnocking. Thanks for the reports!
